- src/utils/supabase/client.ts
- src/utils/supabase/middleware.ts
- src/utils/supabase/server.ts
> add supabase logic

- src/components/form/ParticipationForm.tsx
- src/components/home/RecruitCard.tsx
- src/components/home/RecruitList.tsx
> 메인 페이지 정렬/필터 기능 완성

- src/app/(root)/(protected)/chat/[id]/page.tsx
- src/app/page.tsx
- src/components/auth/SignUpForm.tsx
- src/components/chat/Chat.tsx
- src/components/chat/Sidebar.tsx
- src/components/chat/SidebarToggle.tsx
[#40] add: 채팅 페이지 사이드바 추가 && 회원가입 에러 처리
> [#40] add: 채팅 페이지 사이드바 추가 && 회원가입 에러 처리

- src/app/(root)/(protected)/chat/[id]/page.tsx
- src/components/chat/Chat.tsx
- src/components/chat/MemberList.tsx
- src/components/chat/SendMessageForm.tsx
- src/components/chat/Sidebar.tsx
- src/components/chat/SidebarToggle.tsx
- src/store/followUnfollow.ts
- src/types/partyInfo.ts
- src/types/teamUserProfile.ts
- src/utils/viewStatus.ts
- 채팅창 필수 기능 구현 완료
- 충돌 해결
- 코드 리팩토링 및 추가 기능 구현 예정
>  [#40]: add 채팅창 필수 기능 구현 완료 및 충돌 해결

- src/app/(auth)/signup/page.tsx
- src/app/(root)/(protected)/chat/[id]/page.tsx
- src/app/globals.css
- src/components/auth/SignUpForm.tsx
- src/components/chat/Chat.tsx
- src/components/chat/MemberList.tsx
- src/components/chat/SendMessageForm.tsx
- src/components/chat/Sidebar.tsx
- src/customCss/input/input.ts
> hbeom00 > 1차 병합

- src/app/(root)/party/[id]/(components)/PartyBottom.tsx
- src/app/globals.css
- src/customCSS/platform.ts
> fix:global.css 수정

- src/app/(root)/(protected)/recruit/nextPage/page.tsx
- src/app/(root)/party/[id]/(components)/ExitButton.tsx
- src/app/(root)/party/[id]/(components)/InvitedButton.tsx
- src/app/(root)/party/[id]/(components)/MemberList.tsx
- src/app/(root)/party/[id]/page.tsx
- src/app/globals.css
- src/app/page.tsx
- src/components/button/LogoutButton.tsx
- src/components/home/RecruitCard.tsx
- src/components/home/RecruitList.tsx
- src/components/layout/GoRecruitButton.tsx
- src/components/layout/Header.tsx
- src/components/layout/MyProfileButton.tsx
- src/components/styleComponents/WatchingLabel.tsx
- src/utils/invite.ts
- src/utils/transPlatform.ts
fix:여러 css 작업들(모달,드롭다운, 검색결과...)
> fix:여러 css 작업들(모달,드롭다운, 검색결과...)

- src/app/(root)/(protected)/chat/[id]/page.tsx
- src/app/globals.css
- src/components/chat/Chat.tsx
- src/components/chat/SendMessageForm.tsx
> fix: 채팅 페이지 코드 수정

- src/components/chat/Chat.tsx
> fix: 채팅페이지 공지 기능 위치 고정

- src/app/(root)/(protected)/chat/[id]/page.tsx
- src/components/chat/Chat.tsx
> 채팅페이지 2차 코드 수정

- src/components/chat/Chat.tsx
> fix: 채팅 페이지 오류 해결

- src/components/chat/Chat.tsx
- src/types/chatInfo.ts
> 채팅창 상단에 마진 적용

- src/components/chat/Chat.tsx
> 채팅창 아랫부분 짤림 이슈 해결

- src/app/(root)/(protected)/chat/[id]/page.tsx
- src/app/globals.css
- src/components/button/PlayBar.tsx
- src/components/chat/Chat.tsx
- src/components/chat/Notify.tsx
- src/components/chat/SendMessageForm.tsx
- src/components/chat/SidebarToggle.tsx
update: 채팅 페이지 코드 구조 변경 및 스타일 수정
> update: 채팅 페이지 코드 구조 변경 및 스타일 수정

- src/components/chat/Sidebar.tsx
> add: 파티 강퇴 시 해당 유저 저장하는 로직 생성

- src/components/chat/Chat.tsx
- src/components/chat/SendMessageForm.tsx
> chat.tsx 코드 복구

- src/components/chat/Chat.tsx
- src/components/chat/SendMessageForm.tsx
- src/components/chat/Sidebar.tsx
- src/reactQuery/queryFunc/chat/getPartyMemberList.ts
- src/reactQuery/queryKeys.ts
- src/utils/hooks/useLiveMessage.ts
- src/utils/hooks/useLiveSubscribe.ts
- 채팅 업로드 안됨 현상 해결
- 입/퇴장 기능 수정
> 채팅 페이지 이슈 해결

- src/components/button/PlayBar.tsx
- src/components/chat/Chat.tsx
- src/components/chat/MemberList.tsx
- src/utils/hooks/useLiveMessage.ts
- src/utils/hooks/useLiveSubscribe.ts
- 재생바 에러 해결 ⭕
- 사이드바 멤버 리스트 정렬 ⭕
- 채팅 메세지 길이 제한 ⭕
> 재생바 에러 해결 및 사이드바 멤버 리스트 정렬 및 채팅 메세지 길이 제한 완료

- src/app/(root)/party/[id]/(components)/DetailInfo.tsx
- src/app/(root)/party/[id]/(components)/PartyBottom.tsx
- src/components/home/RecruitCard.tsx
- src/components/layout/HeaderMobileBottom.tsx
> fix:모바일 헤더 등 css 수정

- src/app/globals.css
- src/components/auth/SignInForm.tsx
- 로그인에 실패하면 모달 창 띄우기⭕
- input창에 자동완성으로 텍스트를 삽입하면 input 영역이 파란색으로 바뀌는 현상 제거⭕
> 로그인/회원가입 모달 창 추가 및 input 크롬 기본 속성 제거
